name: Basic CI Pipeline

on:
  push:
    paths:
      - '01-pipeline-foundation/**'
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 01-pipeline-foundation


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -l

      - name: Echo Message
        run: echo "Pipeline is working"

      