name: Security and Secrets

on:
  push:
    paths: 
      - '03-security-secrets/**'
    branches:
      - main
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 03-security-secrets

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t security-secrets .

      - name: Set Secrets
        run: echo "API_KEY=MY-SUPER-SECRET-KEY" >> $GITHUB_ENV

      - name: Run Image
        run: docker run -d --name prod-container -p 5000:5000 -e API_KEY=$API_KEY security-secrets

      - name: Show logs
        run: docker logs prod-container

      - name: Wait for app (Fail if not ready)
        run: |
          for i in {1..10};do
            if curl -fs http://localhost:5000; then
              echo "App is Up"
              exit 0

            fi 
              echo "Wait for app..."
              sleep 2
            done

          echo "App fail to start"
          exit 1

      - name: Real Health Check
        run: curl -f http://localhost:5000

      - name: Cleanup containers
        if: always()
        run: docker stop prod-container && docker rm prod-container